export type ReferenceOption = {
  value: string;
  label: string;
  subtitle?: string;
};

export const COUNTRY_OPTIONS: ReferenceOption[] = [
  { value: 'US', label: 'United States', subtitle: 'US' },
  { value: 'GB', label: 'United Kingdom', subtitle: 'GB' },
  { value: 'FR', label: 'France', subtitle: 'FR' },
  { value: 'NG', label: 'Nigeria', subtitle: 'NG' },
  { value: 'JM', label: 'Jamaica', subtitle: 'JM' },
  { value: 'MX', label: 'Mexico', subtitle: 'MX' },
  { value: 'ES', label: 'Spain', subtitle: 'ES' },
  { value: 'CA', label: 'Canada', subtitle: 'CA' },
  { value: 'DE', label: 'Germany', subtitle: 'DE' },
  { value: 'IT', label: 'Italy', subtitle: 'IT' },
  { value: 'NL', label: 'Netherlands', subtitle: 'NL' },
  { value: 'BR', label: 'Brazil', subtitle: 'BR' },
  { value: 'AR', label: 'Argentina', subtitle: 'AR' },
  { value: 'AU', label: 'Australia', subtitle: 'AU' },
  { value: 'JP', label: 'Japan', subtitle: 'JP' },
  { value: 'KR', label: 'South Korea', subtitle: 'KR' },
  { value: 'ZA', label: 'South Africa', subtitle: 'ZA' },
  { value: 'GH', label: 'Ghana', subtitle: 'GH' },
  { value: 'KE', label: 'Kenya', subtitle: 'KE' },
  { value: 'EG', label: 'Egypt', subtitle: 'EG' },
  { value: 'MA', label: 'Morocco', subtitle: 'MA' },
  { value: 'IN', label: 'India', subtitle: 'IN' },
  { value: 'CN', label: 'China', subtitle: 'CN' },
  { value: 'AE', label: 'United Arab Emirates', subtitle: 'AE' },
  { value: 'QA', label: 'Qatar', subtitle: 'QA' },
  { value: 'SA', label: 'Saudi Arabia', subtitle: 'SA' },
  { value: 'TR', label: 'Turkey', subtitle: 'TR' },
  { value: 'PT', label: 'Portugal', subtitle: 'PT' },
  { value: 'SE', label: 'Sweden', subtitle: 'SE' },
  { value: 'NO', label: 'Norway', subtitle: 'NO' },
  { value: 'DK', label: 'Denmark', subtitle: 'DK' },
  { value: 'BE', label: 'Belgium', subtitle: 'BE' },
  { value: 'CH', label: 'Switzerland', subtitle: 'CH' },
  { value: 'IE', label: 'Ireland', subtitle: 'IE' },
  { value: 'AT', label: 'Austria', subtitle: 'AT' },
  { value: 'PL', label: 'Poland', subtitle: 'PL' },
  { value: 'CZ', label: 'Czech Republic', subtitle: 'CZ' },
  { value: 'HU', label: 'Hungary', subtitle: 'HU' },
  { value: 'RO', label: 'Romania', subtitle: 'RO' },
  { value: 'GR', label: 'Greece', subtitle: 'GR' },
  { value: 'CL', label: 'Chile', subtitle: 'CL' },
  { value: 'CO', label: 'Colombia', subtitle: 'CO' },
  { value: 'PE', label: 'Peru', subtitle: 'PE' },
  { value: 'UY', label: 'Uruguay', subtitle: 'UY' },
  { value: 'EC', label: 'Ecuador', subtitle: 'EC' },
  { value: 'CR', label: 'Costa Rica', subtitle: 'CR' },
  { value: 'PA', label: 'Panama', subtitle: 'PA' },
  { value: 'DO', label: 'Dominican Republic', subtitle: 'DO' },
  { value: 'TT', label: 'Trinidad and Tobago', subtitle: 'TT' },
  { value: 'SN', label: 'Senegal', subtitle: 'SN' },
  { value: 'CI', label: "Cote d'Ivoire", subtitle: 'CI' },
  { value: 'CM', label: 'Cameroon', subtitle: 'CM' },
  { value: 'TZ', label: 'Tanzania', subtitle: 'TZ' },
  { value: 'UG', label: 'Uganda', subtitle: 'UG' },
  { value: 'ZW', label: 'Zimbabwe', subtitle: 'ZW' },
  { value: 'NZ', label: 'New Zealand', subtitle: 'NZ' },
  { value: 'SG', label: 'Singapore', subtitle: 'SG' },
  { value: 'TH', label: 'Thailand', subtitle: 'TH' },
  { value: 'MY', label: 'Malaysia', subtitle: 'MY' },
  { value: 'ID', label: 'Indonesia', subtitle: 'ID' },
  { value: 'PH', label: 'Philippines', subtitle: 'PH' },
  { value: 'VN', label: 'Vietnam', subtitle: 'VN' }
];

export const TIMEZONE_OPTIONS: ReferenceOption[] = [
  { value: 'UTC', label: 'UTC' },
  { value: 'Europe/Paris', label: 'Europe/Paris' },
  { value: 'Europe/London', label: 'Europe/London' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin' },
  { value: 'Europe/Rome', label: 'Europe/Rome' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos' },
  { value: 'Africa/Accra', label: 'Africa/Accra' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo' },
  { value: 'America/New_York', label: 'America/New_York' },
  { value: 'America/Chicago', label: 'America/Chicago' },
  { value: 'America/Denver', label: 'America/Denver' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles' },
  { value: 'America/Toronto', label: 'America/Toronto' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo' },
  { value: 'America/Buenos_Aires', label: 'America/Buenos_Aires' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai' },
  { value: 'Asia/Riyadh', label: 'Asia/Riyadh' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland' }
];

export const AIRPORT_OPTIONS: ReferenceOption[] = [
  { value: 'JFK', label: 'John F. Kennedy International', subtitle: 'New York, US' },
  { value: 'EWR', label: 'Newark Liberty International', subtitle: 'Newark, US' },
  { value: 'LAX', label: 'Los Angeles International', subtitle: 'Los Angeles, US' },
  { value: 'ATL', label: 'Hartsfield-Jackson Atlanta International', subtitle: 'Atlanta, US' },
  { value: 'ORD', label: "O'Hare International", subtitle: 'Chicago, US' },
  { value: 'IAD', label: 'Washington Dulles International', subtitle: 'Washington, US' },
  { value: 'MIA', label: 'Miami International', subtitle: 'Miami, US' },
  { value: 'CDG', label: 'Charles de Gaulle Airport', subtitle: 'Paris, FR' },
  { value: 'ORY', label: 'Orly Airport', subtitle: 'Paris, FR' },
  { value: 'LHR', label: 'Heathrow Airport', subtitle: 'London, GB' },
  { value: 'LGW', label: 'Gatwick Airport', subtitle: 'London, GB' },
  { value: 'MAD', label: 'Adolfo Suarez Madrid-Barajas Airport', subtitle: 'Madrid, ES' },
  { value: 'FRA', label: 'Frankfurt Airport', subtitle: 'Frankfurt, DE' },
  { value: 'AMS', label: 'Amsterdam Airport Schiphol', subtitle: 'Amsterdam, NL' },
  { value: 'DXB', label: 'Dubai International', subtitle: 'Dubai, AE' },
  { value: 'DOH', label: 'Hamad International', subtitle: 'Doha, QA' },
  { value: 'LOS', label: 'Murtala Muhammed International', subtitle: 'Lagos, NG' },
  { value: 'ABV', label: 'Nnamdi Azikiwe International', subtitle: 'Abuja, NG' },
  { value: 'YYZ', label: 'Toronto Pearson International', subtitle: 'Toronto, CA' },
  { value: 'YUL', label: 'Montreal-Trudeau International', subtitle: 'Montreal, CA' },
  { value: 'NRT', label: 'Narita International', subtitle: 'Tokyo, JP' },
  { value: 'HND', label: 'Haneda Airport', subtitle: 'Tokyo, JP' },
  { value: 'ICN', label: 'Incheon International', subtitle: 'Seoul, KR' },
  { value: 'SYD', label: 'Sydney Kingsford Smith', subtitle: 'Sydney, AU' },
  { value: 'MEX', label: 'Benito Juarez International', subtitle: 'Mexico City, MX' }
];
